// ============================================================
// Quran surah data — all 114 surahs
// Used for surah picker dropdown and ayah count validation
// ============================================================

export interface Surah {
  number: number;
  name: string;
  arabicName: string;
  totalAyahs: number;
}

export const SURAHS: Surah[] = [
  { number: 1, name: 'Al-Fatihah', arabicName: 'الفاتحة', totalAyahs: 7 },
  { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', totalAyahs: 286 },
  { number: 3, name: 'Aal-E-Imran', arabicName: 'آل عمران', totalAyahs: 200 },
  { number: 4, name: 'An-Nisa', arabicName: 'النساء', totalAyahs: 176 },
  { number: 5, name: 'Al-Maidah', arabicName: 'المائدة', totalAyahs: 120 },
  { number: 6, name: 'Al-Anam', arabicName: 'الأنعام', totalAyahs: 165 },
  { number: 7, name: 'Al-Araf', arabicName: 'الأعراف', totalAyahs: 206 },
  { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', totalAyahs: 75 },
  { number: 9, name: 'At-Tawbah', arabicName: 'التوبة', totalAyahs: 129 },
  { number: 10, name: 'Yunus', arabicName: 'يونس', totalAyahs: 109 },
  { number: 11, name: 'Hud', arabicName: 'هود', totalAyahs: 123 },
  { number: 12, name: 'Yusuf', arabicName: 'يوسف', totalAyahs: 111 },
  { number: 13, name: 'Ar-Rad', arabicName: 'الرعد', totalAyahs: 43 },
  { number: 14, name: 'Ibrahim', arabicName: 'إبراهيم', totalAyahs: 52 },
  { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', totalAyahs: 99 },
  { number: 16, name: 'An-Nahl', arabicName: 'النحل', totalAyahs: 128 },
  { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', totalAyahs: 111 },
  { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', totalAyahs: 110 },
  { number: 19, name: 'Maryam', arabicName: 'مريم', totalAyahs: 98 },
  { number: 20, name: 'Taha', arabicName: 'طه', totalAyahs: 135 },
  { number: 21, name: 'Al-Anbiya', arabicName: 'الأنبياء', totalAyahs: 112 },
  { number: 22, name: 'Al-Hajj', arabicName: 'الحج', totalAyahs: 78 },
  { number: 23, name: 'Al-Muminun', arabicName: 'المؤمنون', totalAyahs: 118 },
  { number: 24, name: 'An-Nur', arabicName: 'النور', totalAyahs: 64 },
  { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', totalAyahs: 77 },
  { number: 26, name: 'Ash-Shuara', arabicName: 'الشعراء', totalAyahs: 227 },
  { number: 27, name: 'An-Naml', arabicName: 'النمل', totalAyahs: 93 },
  { number: 28, name: 'Al-Qasas', arabicName: 'القصص', totalAyahs: 88 },
  { number: 29, name: 'Al-Ankabut', arabicName: 'العنكبوت', totalAyahs: 69 },
  { number: 30, name: 'Ar-Rum', arabicName: 'الروم', totalAyahs: 60 },
  { number: 31, name: 'Luqman', arabicName: 'لقمان', totalAyahs: 34 },
  { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', totalAyahs: 30 },
  { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', totalAyahs: 73 },
  { number: 34, name: 'Saba', arabicName: 'سبأ', totalAyahs: 54 },
  { number: 35, name: 'Fatir', arabicName: 'فاطر', totalAyahs: 45 },
  { number: 36, name: 'Ya-Sin', arabicName: 'يس', totalAyahs: 83 },
  { number: 37, name: 'As-Saffat', arabicName: 'الصافات', totalAyahs: 182 },
  { number: 38, name: 'Sad', arabicName: 'ص', totalAyahs: 88 },
  { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', totalAyahs: 75 },
  { number: 40, name: 'Ghafir', arabicName: 'غافر', totalAyahs: 85 },
  { number: 41, name: 'Fussilat', arabicName: 'فصلت', totalAyahs: 54 },
  { number: 42, name: 'Ash-Shura', arabicName: 'الشورى', totalAyahs: 53 },
  { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', totalAyahs: 89 },
  { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', totalAyahs: 59 },
  { number: 45, name: 'Al-Jathiyah', arabicName: 'الجاثية', totalAyahs: 37 },
  { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', totalAyahs: 35 },
  { number: 47, name: 'Muhammad', arabicName: 'محمد', totalAyahs: 38 },
  { number: 48, name: 'Al-Fath', arabicName: 'الفتح', totalAyahs: 29 },
  { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', totalAyahs: 18 },
  { number: 50, name: 'Qaf', arabicName: 'ق', totalAyahs: 45 },
  { number: 51, name: 'Adh-Dhariyat', arabicName: 'الذاريات', totalAyahs: 60 },
  { number: 52, name: 'At-Tur', arabicName: 'الطور', totalAyahs: 49 },
  { number: 53, name: 'An-Najm', arabicName: 'النجم', totalAyahs: 62 },
  { number: 54, name: 'Al-Qamar', arabicName: 'القمر', totalAyahs: 55 },
  { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', totalAyahs: 78 },
  { number: 56, name: 'Al-Waqiah', arabicName: 'الواقعة', totalAyahs: 96 },
  { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', totalAyahs: 29 },
  { number: 58, name: 'Al-Mujadila', arabicName: 'المجادلة', totalAyahs: 22 },
  { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', totalAyahs: 24 },
  { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', totalAyahs: 13 },
  { number: 61, name: 'As-Saff', arabicName: 'الصف', totalAyahs: 14 },
  { number: 62, name: 'Al-Jumuah', arabicName: 'الجمعة', totalAyahs: 11 },
  { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', totalAyahs: 11 },
  { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', totalAyahs: 18 },
  { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', totalAyahs: 12 },
  { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', totalAyahs: 12 },
  { number: 67, name: 'Al-Mulk', arabicName: 'الملك', totalAyahs: 30 },
  { number: 68, name: 'Al-Qalam', arabicName: 'القلم', totalAyahs: 52 },
  { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', totalAyahs: 52 },
  { number: 70, name: 'Al-Maarij', arabicName: 'المعارج', totalAyahs: 44 },
  { number: 71, name: 'Nuh', arabicName: 'نوح', totalAyahs: 28 },
  { number: 72, name: 'Al-Jinn', arabicName: 'الجن', totalAyahs: 28 },
  { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', totalAyahs: 20 },
  { number: 74, name: 'Al-Muddaththir', arabicName: 'المدثر', totalAyahs: 56 },
  { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', totalAyahs: 40 },
  { number: 76, name: 'Al-Insan', arabicName: 'الإنسان', totalAyahs: 31 },
  { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', totalAyahs: 50 },
  { number: 78, name: 'An-Naba', arabicName: 'النبأ', totalAyahs: 40 },
  { number: 79, name: 'An-Naziat', arabicName: 'النازعات', totalAyahs: 46 },
  { number: 80, name: 'Abasa', arabicName: 'عبس', totalAyahs: 42 },
  { number: 81, name: 'At-Takwir', arabicName: 'التكوير', totalAyahs: 29 },
  { number: 82, name: 'Al-Infitar', arabicName: 'الانفطار', totalAyahs: 19 },
  { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', totalAyahs: 36 },
  { number: 84, name: 'Al-Inshiqaq', arabicName: 'الانشقاق', totalAyahs: 25 },
  { number: 85, name: 'Al-Buruj', arabicName: 'البروج', totalAyahs: 22 },
  { number: 86, name: 'At-Tariq', arabicName: 'الطارق', totalAyahs: 17 },
  { number: 87, name: 'Al-Ala', arabicName: 'الأعلى', totalAyahs: 19 },
  { number: 88, name: 'Al-Ghashiyah', arabicName: 'الغاشية', totalAyahs: 26 },
  { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', totalAyahs: 30 },
  { number: 90, name: 'Al-Balad', arabicName: 'البلد', totalAyahs: 20 },
  { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', totalAyahs: 15 },
  { number: 92, name: 'Al-Layl', arabicName: 'الليل', totalAyahs: 21 },
  { number: 93, name: 'Ad-Duha', arabicName: 'الضحى', totalAyahs: 11 },
  { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', totalAyahs: 8 },
  { number: 95, name: 'At-Tin', arabicName: 'التين', totalAyahs: 8 },
  { number: 96, name: 'Al-Alaq', arabicName: 'العلق', totalAyahs: 19 },
  { number: 97, name: 'Al-Qadr', arabicName: 'القدر', totalAyahs: 5 },
  { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', totalAyahs: 8 },
  { number: 99, name: 'Az-Zalzalah', arabicName: 'الزلزلة', totalAyahs: 8 },
  { number: 100, name: 'Al-Adiyat', arabicName: 'العاديات', totalAyahs: 11 },
  { number: 101, name: 'Al-Qariah', arabicName: 'القارعة', totalAyahs: 11 },
  { number: 102, name: 'At-Takathur', arabicName: 'التكاثر', totalAyahs: 8 },
  { number: 103, name: 'Al-Asr', arabicName: 'العصر', totalAyahs: 3 },
  { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', totalAyahs: 9 },
  { number: 105, name: 'Al-Fil', arabicName: 'الفيل', totalAyahs: 5 },
  { number: 106, name: 'Quraysh', arabicName: 'قريش', totalAyahs: 4 },
  { number: 107, name: 'Al-Maun', arabicName: 'الماعون', totalAyahs: 7 },
  { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', totalAyahs: 3 },
  { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', totalAyahs: 6 },
  { number: 110, name: 'An-Nasr', arabicName: 'النصر', totalAyahs: 3 },
  { number: 111, name: 'Al-Masad', arabicName: 'المسد', totalAyahs: 5 },
  { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', totalAyahs: 4 },
  { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', totalAyahs: 5 },
  { number: 114, name: 'An-Nas', arabicName: 'الناس', totalAyahs: 6 },
];

/** Get a surah by its number (1-indexed) */
export function getSurahByNumber(number: number): Surah | undefined {
  return SURAHS.find((s) => s.number === number);
}

/** Get total ayahs for a surah by number */
export function getTotalAyahs(surahNumber: number): number | undefined {
  return getSurahByNumber(surahNumber)?.totalAyahs;
}
