import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { colors } from '@/lib/colors';
import type { StudentReport, AttendanceSummary, BehaviorSummary } from '@/lib/types';

interface ReportParams {
  studentName: string;
  dateRangeLabel: string;
  report: StudentReport;
  attendance: AttendanceSummary;
  behavior: BehaviorSummary;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function generateReportHTML({
  studentName,
  dateRangeLabel,
  report,
  attendance,
  behavior,
}: ReportParams): string {
  const totalAssignments =
    report.new_lesson.total + report.previous_lesson.total + report.revision.total;
  const totalPassed =
    report.new_lesson.passed + report.previous_lesson.passed + report.revision.passed;
  const overallPassRate =
    totalAssignments > 0 ? Math.round((totalPassed / totalAssignments) * 100) : 0;
  const totalPages =
    report.new_lesson.pages + report.previous_lesson.pages + report.revision.pages;

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, sans-serif; padding: 32px; color: ${colors.charcoal}; }
  h1 { color: ${colors.primary}; font-size: 24px; margin-bottom: 4px; }
  .subtitle { color: ${colors.gray600}; font-size: 14px; margin-bottom: 24px; }
  .section { margin-bottom: 20px; }
  .section-title { font-size: 16px; font-weight: 600; margin-bottom: 8px; border-bottom: 2px solid ${colors.primary}; padding-bottom: 4px; }
  table { width: 100%; border-collapse: collapse; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid ${colors.gray200}; }
  th { background: ${colors.gray100}; font-size: 13px; color: ${colors.gray600}; }
  td { font-size: 14px; }
  .footer { margin-top: 32px; text-align: center; font-size: 11px; color: ${colors.gray400}; }
</style>
</head>
<body>
  <h1>${escapeHtml(studentName)}</h1>
  <div class="subtitle">Progress Report — ${escapeHtml(dateRangeLabel)}</div>

  <div class="section">
    <div class="section-title">Pass Rates</div>
    <table>
      <tr><th>Category</th><th>Passed</th><th>Total</th><th>Rate</th><th>Pages</th></tr>
      <tr><td>New Lesson</td><td>${report.new_lesson.passed}</td><td>${report.new_lesson.total}</td><td>${report.new_lesson.pass_rate}%</td><td>${report.new_lesson.pages}</td></tr>
      <tr><td>Previous Lesson</td><td>${report.previous_lesson.passed}</td><td>${report.previous_lesson.total}</td><td>${report.previous_lesson.pass_rate}%</td><td>${report.previous_lesson.pages}</td></tr>
      <tr><td>Revision</td><td>${report.revision.passed}</td><td>${report.revision.total}</td><td>${report.revision.pass_rate}%</td><td>${report.revision.pages}</td></tr>
      <tr style="font-weight:600"><td>Overall</td><td>${totalPassed}</td><td>${totalAssignments}</td><td>${overallPassRate}%</td><td>${totalPages}</td></tr>
    </table>
  </div>

  <div class="section">
    <div class="section-title">Attendance</div>
    <table>
      <tr><th>Present</th><th>Absent</th><th>Late</th><th>Left Early</th><th>Total</th></tr>
      <tr><td>${attendance.present}</td><td>${attendance.absent}</td><td>${attendance.late}</td><td>${attendance.left_early}</td><td>${attendance.total}</td></tr>
    </table>
  </div>

  <div class="section">
    <div class="section-title">Behavior</div>
    <table>
      <tr><th>Very Good</th><th>Good</th><th>Needs Improvement</th><th>Total</th></tr>
      <tr><td>${behavior.very_good}</td><td>${behavior.good}</td><td>${behavior.needs_improvement}</td><td>${behavior.total}</td></tr>
    </table>
  </div>

  <div class="footer">Generated by Hifdh Tracker — Qalam Institute</div>
</body>
</html>`;
}

export async function shareReport(params: ReportParams): Promise<void> {
  const html = generateReportHTML(params);
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: `${params.studentName} Report`,
    UTI: 'com.adobe.pdf',
  });
}
